### Create a new user
 POST http://localhost:5000/api/users
Content-Type: application/json

{
  "id": 1231231232,
  "first_name": "Sara",
  "second_name": "Ali",
  "third_name": "Hassan",
  "last_name": "Alzahrani",
  "email": "sara@example.com",
  "password": "123456",
  "role": "student",
  "school_id": null,
  "phone": "0560000000"
}

### Get all users
GET http://localhost:5000/api/users
